# Generated by Django 3.1.5 on 2021-01-04 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Writing',
        ),
    ]
