# Generated by Django 3.1.5 on 2021-01-04 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_auto_20210105_0332'),
    ]

    operations = [
        migrations.AddField(
            model_name='writing',
            name='image',
            field=models.ImageField(null=True, upload_to='media'),
        ),
    ]
