# Generated by Django 3.1.5 on 2021-01-04 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_writing_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writing',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
