# Generated by Django 3.1.5 on 2021-01-08 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0004_auto_20210105_0429'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('contents', models.TextField(max_length=1000)),
                ('image', models.ImageField(null=True, upload_to='')),
            ],
        ),
    ]
