# Generated by Django 3.1.5 on 2021-01-08 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0005_diary'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='numLikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='diary',
            name='numViews',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='diary',
            name='openPoint',
            field=models.IntegerField(default=0),
        ),
    ]
