# Generated by Django 3.1.5 on 2021-01-08 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0006_auto_20210108_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='image',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
