# Generated by Django 3.1.5 on 2021-01-08 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0007_auto_20210108_2201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diary',
            name='image',
        ),
        migrations.CreateModel(
            name='DiaryImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='')),
                ('linkedDiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload.diary')),
            ],
        ),
    ]
