# Generated by Django 3.1.5 on 2021-01-08 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0008_auto_20210108_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writing',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
