# Generated by Django 3.1.5 on 2021-01-08 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0009_auto_20210108_2230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diaryimage',
            name='linkedDiary',
        ),
        migrations.AddField(
            model_name='diaryimage',
            name='diary',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='upload.diary'),
        ),
        migrations.AlterField(
            model_name='diaryimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
