# Generated by Django 3.1.5 on 2021-01-08 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0013_auto_20210108_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='writtenDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
